version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo 
    ports:
      - "27017:27017"
    volumes:
      - ../../:/workspace
volumes:
  pgdata:
